---
kind: pipeline
name: Build-And-Publish
type: docker

trigger:
  branch:
    - main
    - develop

steps:
  - name: Build & Test Codebase
    image: node:lts-alpine
    commands:
      - npm install
      - npm run build
      - npm test

  - name: Perform Snyk Scans
    image: node:lts-alpine
    environment:
      SNYK_TOKEN:
        from_secret: SNYK_TOKEN
    commands:
      - npm install
      - snyk monitor
      - snyk code

# ---
# kind: pipeline
# name: Perform-Scheduled-Snyk-Scans
# type: docker

# trigger:
#   event:
#     - cron
#   target:
#     include:
#       - weekly
#       - nightly
#   branch:
#     include:
#       - main
#       - develop

# steps:
#   - name: Perform Snyk Scans
#     image: node:lts-alpine
#     environment:
#       SNYK_TOKEN:
#         from_secret: SNYK_TOKEN
#     commands:
#       - npm install
#       - snyk monitor
#       - snyk code

# ---
# kind: template
# load: Build-And-Publish-TS-Module.yaml
# data:
#   repoOwner: 4lch4
#   repoName: Cronicle-Plugin-Tools
