---
kind: pipeline
name: default
type: docker

steps:
  - name: Build & Test Codebase
    image: node:lts-alpine
    commands:
      - npm install
      - npm run build
      - npm test

  - name: Execute Snyk Scans
    image: node:lts-alpine
    environment:
      SNYK_TOKEN:
        from_secret: SNYK_TOKEN
    commands:
      - echo $SNYK_TOKEN
      - snyk auth $SNYK_TOKEN
      - snyk monitor
      - snyk code test
# ---
# kind: template
# load: Build-And-Publish-TS-Module.yaml
# data:
#   repoOwner: 4lch4
#   repoName: Cronicle-Plugin-Tools
